const comps = [
  {
    name: "SKO No Pro Open 2021 (Beginner)",
    id: "sko-2021-npo-1-beginner",
    tricks: [
      "Basecup, spike (ken grip)",
      "Around the block",
      "Swing spike",
      "Trapeze",
      "Airplane",
      "Baseball (catch in Basecup)",
      "Stuntplane",
      "Small cup, Orbit to Big cup, Spike",
      "Easy Lighthouse, falling in",
      "Around Japan",
      "Switch pull up to Small cup",
      "Spike, Earthturn",
      "Moshikame x10",
      "Frying pan, Spike",
      "Big cup, Knee bounce, Big cup, Spike",
    ],
  },
  {
    name: "SKO No Pro Open 2021 (Intermediate)",
    id: "sko-2021-npo-1-intermediate",
    tricks: [
      "Airplane inward J-stick",
      "Around europe",
      "Bird, flip over valley, in ",
      "Down Spike, Base cup, down spike",
      "One turn airplane",
      "Stunt Plane Fast hands",
      "Lighthouse,Trade spike",
      "Big cup ken flip bigcup, spike",
      "Turntable, spike",
      "Gunslinger to spike",
      "Lunar, in",
      "Swing Penguin Spike",
      "Candle stick, Trade spike",
      "Whirlwind",
      "Switch Swing spike",
    ],
  },
  {
    name: "SKO No Pro Open 2021 (Advanced)",
    id: "sko-2021-npo-1-advanced",
    tricks: [
      "One turn Lighthouse, flip trade spike",
      "Handle stall, Flip in",
      "Lunar, Lunar flip, flip in ",
      "Juggle to spike ",
      "Downspike fast hands, J-stick",
      "Penguin, grip switch downspike",
      "Two turn Airplane",
      "Space walk one turn in",
      "Bird, trade downspike",
      "Around USA",
      "Double kenflip to spike",
      "Stilt over valley in",
      "Lightning Drop Trade spike",
      "Lighthouse, flip tap House, in",
      "Inward lunar, inward flip in",
    ],
  },
  {
    name: "SKO No Pro Open 2021 (Open)",
    id: "sko-2021-npo-1-open",
    tricks: [
      "Inward axe, inward lunar in",
      "Two turn Airplane, double tap flip to in",
      "Bird, flip over valley, trade downspike ",
      "Scramble one turn trade spike",
      "Stuntplane, 1.5 swap downspike",
      "Triple LH flip, in",
      "Double slinger to spike, Dub Whirlslinger",
      "Around Down USA",
      "Switch Airplane, J-stick. ",
      "Downspike fast, slide out to Candle, trade spike",
      "Double whirlwind (either way) ",
      "Lunar, Lunar flip, 180 rover, Inward lunar flip, in",
      "Airplane, 1.5 swap to bird, in",
      "Tap juggle spike",
      "Stilt, Stilt flip, in",
    ],
  },
  {
    name: "SKO No Pro Open 2021 (Top 16 Open)",
    id: "sko-2021-npo-1-open-t16",
    tricks: [
      "Inward lunar, flip wong tap to lunar, in",
      "Slinger, juggle, late slinger spike",
      "Lighthouse, Trade Candle, Toss to lighthouse insta trade spike",
      "One turn Stunt Fast",
      "Handle stall, Nightingale, Bird, Inward flip in",
      "One turn cush tap lighthouse, flip cush tap lighthouse, half flip cush in",
      "Airplane, 1.5 trade, 2 turn throw in",
      "Sara Base cup, Ken flip downspike",
      "Inward stilt, half flip to LH insta half flip reg stilt, Trade Down spike Fast Hands",
      "Bird Juggle over the valley, in",
      "Airplane, slide candle grip 1.5 throw to Light house, in ",
      "Ken Late ken Spike, ken late ken spike  ",
      "Triple tap juggle spike",
      "Down Spike Down Whirl ",
      "Around Stunt Plane",
    ],
  },
];

export default comps;
