const comps = [
  {
    name: "Sakura Summer 2021 (Beginner)",
    id: "sso-2021-1-beginner",
    tricks: [
      "Swing Candle Stick",
      "Vacuum",
      "Lady Bug",
      "Lighthouse - Falling in",
      "Funhouse - Spike",
      "Frying Pan - Spike",
      "Swing Spike - Earthturn",
      "Bird - Spike",
      "Around Japan",
      "Praying Mantis",
      "Ken Drop",
      "Airplane - Jumping Stick",
      "Moshikame x 15 - Spike",
    ],
  },
  {
    name: "Sakura Summer 2021 (Intermediate)",
    id: "sso-2021-1-intermediate",
    tricks: [
      "Big cup - Knee bounce - Base cup - Down spike",
      "Around the block (Candlestrick grip)",
      "One turn airplane",
      "Around Europe",
      "Hanging Spike",
      "Flying top - Bungee - Kenflip - Spike",
      "Stuntplane",
      "Bird over the valley - in",
      "Lighthouse flip - in",
      "Vacuum - Flip - Vacuum",
      "Inward lunar - Inward falling in",
      "Base cup centrifugal force - Penguin - Spike",
      "Baseball - Basecup - Downspike",
    ],
  },
  {
    name: "Sakura Summer 2021 (Open)",
    id: "sso-2021-1-open",
    tricks: [
      "Around USA",
      "Around the Garden",
      "Whirlwind",
      "Mooncircle Spike",
      "Spacewalk - 1 turn in",
      "Half goon - 1 turn in",
      "1 turn tap - 1 turn in",
      "Candle grip swing ken grip spike",
      "Vacuum cleaner - Trade spike",
      "Double lunar flip",
      "UFO Mateo spin",
      "Kush Countdown (2 turn kush in - 1.5 kush in - 0.5 kush in)",
      "Ken grip swap 0.5 airplane - 0.5 swap",
      "Swing sling late half flip sara grip down spike",
      "Shima Cobb Spike",
      "Lunar Barrel Roll - in",
      "Inward lunar - Inward lunar flip - Inward flip in",
      "Hanging spike",
      "Bird over the valley x2",
      "Double tap 1 turn in",
      "Airplane - Whirlpool - Ken grip spike",
      "Migration (Pull up bird - switch hand spike - normal hand little bird - switch hand spike) no tama rotation",
      "Airplane - 3 insta lighthouse flips - falling in",
      "The Lunar One with the Stilts (Inward lunar -  0.5 turn to small cup lunar -  hop to inward stilt - flip stilt - in)",
      "Tailwhip, airplane or stuntplane",
      "Big cup - pirouette big cup - spike",
    ],
  },
  {
    name: "SKO No Pro Open 2021 (Beginner)",
    id: "sko-2021-npo-1-beginner",
    tricks: [
      "Basecup, spike (ken grip)",
      "Around the block",
      "Swing spike",
      "Trapeze",
      "Airplane",
      "Baseball (catch in Basecup)",
      "Stuntplane",
      "Small cup, Orbit to Big cup, Spike",
      "Easy Lighthouse, falling in",
      "Around Japan",
      "Switch pull up to Small cup",
      "Spike, Earthturn",
      "Moshikame x10",
      "Frying pan, Spike",
      "Big cup, Knee bounce, Big cup, Spike",
    ],
  },
  {
    name: "SKO No Pro Open 2021 (Intermediate)",
    id: "sko-2021-npo-1-intermediate",
    tricks: [
      "Airplane inward J-stick",
      "Around europe",
      "Bird, flip over valley, in ",
      "Down Spike, Base cup, down spike",
      "One turn airplane",
      "Stunt Plane Fast hands",
      "Lighthouse,Trade spike",
      "Big cup ken flip bigcup, spike",
      "Turntable, spike",
      "Gunslinger to spike",
      "Lunar, in",
      "Swing Penguin Spike",
      "Candle stick, Trade spike",
      "Whirlwind",
      "Switch Swing spike",
    ],
  },
  {
    name: "SKO No Pro Open 2021 (Advanced)",
    id: "sko-2021-npo-1-advanced",
    tricks: [
      "One turn Lighthouse, flip trade spike",
      "Handle stall, Flip in",
      "Lunar, Lunar flip, flip in ",
      "Juggle to spike ",
      "Downspike fast hands, J-stick",
      "Penguin, grip switch downspike",
      "Two turn Airplane",
      "Space walk one turn in",
      "Bird, trade downspike",
      "Around USA",
      "Double kenflip to spike",
      "Stilt over valley in",
      "Lightning Drop Trade spike",
      "Lighthouse, flip tap House, in",
      "Inward lunar, inward flip in",
    ],
  },
  {
    name: "SKO No Pro Open 2021 (Open)",
    id: "sko-2021-npo-1-open",
    tricks: [
      "Inward axe, inward lunar in",
      "Two turn Airplane, double tap flip to in",
      "Bird, flip over valley, trade downspike ",
      "Scramble one turn trade spike",
      "Stuntplane, 1.5 swap downspike",
      "Triple LH flip, in",
      "Double slinger to spike, Dub Whirlslinger",
      "Around Down USA",
      "Switch Airplane, J-stick. ",
      "Downspike fast, slide out to Candle, trade spike",
      "Double whirlwind (either way) ",
      "Lunar, Lunar flip, 180 rover, Inward lunar flip, in",
      "Airplane, 1.5 swap to bird, in",
      "Tap juggle spike",
      "Stilt, Stilt flip, in",
    ],
  },
  {
    name: "SKO No Pro Open 2021 (Top 16 Open)",
    id: "sko-2021-npo-1-open-t16",
    tricks: [
      "Inward lunar, flip wong tap to lunar, in",
      "Slinger, juggle, late slinger spike",
      "Lighthouse, Trade Candle, Toss to lighthouse insta trade spike",
      "One turn Stunt Fast",
      "Handle stall, Nightingale, Bird, Inward flip in",
      "One turn cush tap lighthouse, flip cush tap lighthouse, half flip cush in",
      "Airplane, 1.5 trade, 2 turn throw in",
      "Sara Base cup, Ken flip downspike",
      "Inward stilt, half flip to LH insta half flip reg stilt, Trade Down spike Fast Hands",
      "Bird Juggle over the valley, in",
      "Airplane, slide candle grip 1.5 throw to Light house, in ",
      "Ken Late ken Spike, ken late ken spike  ",
      "Triple tap juggle spike",
      "Down Spike Down Whirl ",
      "Around Stunt Plane",
    ],
  },
  {
    name: "IKO 2021 AM",
    id: "iko-2021-1-am",
    tricks: [
      "Stuntplane fasthand penguin",
      "Handle stall - nightingale - spike",
      "Swing spike - base cup sara grip - down spike fast hand",
      "Whirlwind - inward whirlwind",
      "Juggle spike",
      "Sling penguin base cup - spike",
      "Lunar .5 rover to inward lunar - one turn in",
      "Turntable - spike",
      "Big cup - knee bounce - big cup - spike",
      "Single earthturn - double earthturn",
      "Airplane - inward jumping stick ",
      "Airplane - 1.5 swap spike",
      "Airplane - lunar - lunar flip - one turn in",
      "Inward stilt - lighthouse - in",
      "Wing - in",
      "Switch lighthouse - in",
      "Underbird - nod off - nod on - spike",
      "Axe - in",
      "OG .5 tap in",
      "Downspike - down earthturn",
    ],
  },
  {
    name: "IKO 2021 Pro",
    id: "iko-2021-1-pro",
    tricks: [
      "Inward lunar - monkey spike tap inward lunar - inward tradespike",
      "Juggle ghost stuntplane fasthand",
      "Airplane - 1.5 swap to handlestall - airplane",
      "Airplane - inward .5 toss inward .5 in ",
      "Triple jumping stick fasthand",
      "Penguin handlestall - flip - in",
      "Triple kenflip ghost jug x3",
      "Double tap cushion lighthouse - stuntplane fasthand",
      "Quad lunar flip - in",
      "Airplane - toss to airplane fasthand ",
      "Sling jug late sling in",
      "Finger boarder in",
      "Double stilt flip - in",
      "Cushion tap swap cushion tap in",
      "Inward lunar - belly flop - inward lunar - in",
      "Switch juggle spike",
      "Insta lighthouse x3 one turn trade spike",
      ".5 string pinch ",
      "Airplane - knee bounce inward 1.5 in",
      "Lunar laser flip - in",
    ],
  },
  {
    name: "BATB 2021 Beginner",
    id: "batb-2021-1-beginner",
    tricks: [
      "Swing Spike",
      "Candlestick",
      "Big Cup Orbit",
      "Around the Block",
      "Big Cup, Spike",
      "Big Cup, Clack, Big Cup",
      "Pull Up Spike",
      "Penguin Catch",
      "Airplane",
      "Around Japan",
      "Moshikame x 5",
      "Sara Grip Spike",
      "Big Cup, Knee Bounce, Big Cup",
      "Rising Dragon ",
      "Hanging Stunt Plane Snatch",
    ],
  },
  {
    name: "BATB 2021 Intermediate",
    id: "batb-2021-1-intermediate",
    tricks: [
      "Airplane, Jumping Stick",
      "Swing Spike, Earth Turn",
      "Trapeze, In",
      "Stunt Plane",
      "Big Cup, Kenflip, Big Cup, Spike",
      "One Turn Airplane",
      "Around the World Sara Grip",
      "Downspike",
      "Slip on Stick",
      "Around Europe",
      "Airplane, Bottom Cup, Spike",
      "Bird, in",
      "Hanging Lighthouse, Falling In",
      "Gunslinger Spike",
      "Lighthouse, Trade Spike",
    ],
  },
  {
    name: "BATB 2021 Advanced",
    id: "batb-2021-1-advanced",
    tricks: [
      "Swing Spike, Whirlwind",
      "Underbird, Spike",
      "Lunar Flip, In",
      "Airplane, Tap Reverse Flip In",
      "Lighthouse Flip, Trade Spike",
      "Sweet Special",
      "Turntable, Spike",
      "Stunt Plane Fasthand",
      "Airplane, UFO",
      "Stilt, Trade Downspike",
      "Handle Stall, Spike",
      "Candlestick, Swap Spike",
      "Spacewalk, One Turn In",
      "Opposite Hand Swing Spike, Earth Turn",
      "Inward Lunar, Flip In",
    ],
  },
  {
    name: "BATB 2021 Open",
    id: "batb-2021-1-open",
    tricks: [
      "Three Turn LH, Falling In Fasthand",
      "Inward Stilt Flip, Falling In",
      "OG Tap to LH, OG Tap 1.5 In",
      "Lunar Barrel Roll, Falling In",
      "Swing Spike, 1.5 Juggle Downspike",
      "Underbird Nod-Off, Bird Nod-Off, Spike",
      "Airplane, 1.5 Swap Late Kenflip Spike",
      "Gooncircle Juggle Spike",
      "Inward Lunar Rover, In",
      "Two Turn, Tap Juggle Spike",
      "Airplane, One Turn Swap Downspike Fast",
      "Swing Spike, UFO Whirlwind",
      "Airplane, Tap Swap Throw In",
      "GS Spike, Loaded Revolver, GS Spike",
      "Airplane, 1.5 to LH, Flip Tap LH, 1.5 in",
    ],
  },
  {
    name: "BATB 2021 Open (Top 8)",
    id: "batb-2021-1-open-t8",
    tricks: [
      "Candlestick, LH, Candlestick, Trade Spike",
      "Stunt Plane, ET to Penguin FH Ken Grip Spike",
      "LH, Reg Insta Inward Insta Reg LH, In",
      "Lunar, Juggle, Ghost Lunar, In",
      "Opposite Hand Airplane, Cushion Tap",
      "Spacewalk One Turn Lunar, Tré Flip, Trade Spike",
      "Hanging Swing Cushion IL, Flip Cushion In",
      "Trip Jumping Stick, Reverse Trip Jumping Stick",
      "Handle Stall, Ring Stall, Bird, Nightingale, In",
      "Juggle Candle Juggle Spike",
      "Bird Juggle Bird, Spike",
      "Sweets Special, Opposite Hand Spike",
      "LH, Inward Flip, Inward Toss LH, Inward Falling In",
      "Inward Lunar Backflip, Tap Juggle Spike",
      "Stilt Monkey Tap, Downspike ",
    ],
  },
  {
    name: "NAKO 2020 Beginner",
    id: "nako-2020-1-beginner",
    tricks: [
      "Candlestick",
      "Bottom Cup ",
      "Trapeze",
      "Big Cup",
      "Moshikame x5",
      "Frying Pan Spike ",
      "Big Cup Bungee Bug Cup",
      "Big Cup Orbit Big Cup",
      "Easy Spike - Earth Turn ",
      "Spike, Flying Top, Spike ",
      "Around Japan",
      "Airplane",
      "Spike (No Spin)",
      "Baseball",
      "Small cup",
    ],
  },
  {
    name: "NAKO 2020 Intermediate",
    id: "nako-2020-1-intermediate",
    tricks: [
      "Bird - Spike ",
      "Downspike",
      "Lighthouse Falling In",
      "Around The World",
      "One Turn Airplane ",
      "Stuntplane",
      "Swing Spike - Inward Earth",
      "Big Cup, Knee Bounce, Bottom Cup, Spike",
      "Airplane UFO",
      "Opposite Hand Airplane",
      "Around the Block (candle stick grip)",
      "Airplane Jumping Stick",
      "Hanging Spike",
      "Big cup, Double Orbit to big cup, Spike",
      "Moshikame x10",
    ],
  },
  {
    name: "NAKO 2020 Advanced",
    id: "nako-2020-1-advanced",
    tricks: [
      "Handle Stall - Spike",
      "C-Whip - Airplane",
      "Lunar - In",
      "Spike - Whirlwind",
      "Airplane - Inward J Stick - Reg J Stick",
      "Stunt Plane Fast Hands",
      "Bird Over Valley - Spike",
      "Lighthouse - Lighthouse Flip - In",
      "Juggle to Big Cup - Spike",
      "Spike - Earth - Inward Earth",
      "Stilt - In",
      "Spacewalk",
      "Around Europe - Earth Turn",
      "Base Cup - Downspike Fast Hands (Sara grip)",
      "Moon Circle to Spike",
    ],
  },
  {
    name: "NAKO 2020 AM Open",
    id: "nako-2020-1-am",
    tricks: [
      "Inward Lunar Flip - In",
      "Around the USA",
      "Gunslinger - Earth Turn",
      "Handlestall, Spike",
      "Hanging Airplane",
      "Opposite Hand Underbird",
      "Airplane Dub Inward J Stick",
      "Airplane Tap Airplane",
      "1 Turn Lighthouse - Inward Lighthouse flip - Reg Lighthouse flip - Tradespike",
      "Stilt Flip - In",
      "Juggle Spike",
      "Around Downspike (Sara Grip)",
      "Lightning Drop Tradespike",
      "Double Gunslinger",
      "Lunar Tre",
      "Kenflip Bottom Cup - 1.5 Flip to Lighthouse - Flip Trade Spike",
      "Sweets Special",
      "Around Underbird",
      "Dub Inward Whirlwind",
      "Double Stuntplane flip ",
      "Candle Grip Underbird - Flip Over Valley - Trade Ken Grip Spike",
    ],
  },
  {
    name: "NAKO 2020 Open (Level 1)",
    id: "nako-2020-1-open-l1",
    tricks: [
      "Airplane 2-Tap Airplane",
      "Kenflip Underbird - Kenflip Spike",
      "Spacewalk to Lunar - Trade Downspike",
      "Hanging Lighthouse - Insta Lighthouse Flip - Tradespike",
      "Hanging Penguin Spike",
      "Lunar Flip - REVERSE HOP to small cup - Inward Lunar Flip - In",
      "Juggle to Bird",
      "Inward Double J Stick",
      "Juggle late Kenflip Spike",
      "Inward Lunar Barrell Roll",
      "Hippie Flip to Lighty - In",
    ],
  },
  {
    name: "NAKO 2020 Open (Level 2)",
    id: "nako-2020-1-open-l2",
    tricks: [
      "Switch Inward Lunar Flip - Flip In",
      "Turn Table - Reverse Turn Table - In",
      "Double Ken Flip Handlestall",
      "Airplane 1.5 Trade Throw to Airplane",
      "Double Stuntplane Flip",
      "2 turn in - insta double j stick",
      "Triple Gunslinger",
      "Lighthouse - Insta inward lighthouse flip, insta inward, insta inward - Inward falling in",
      "Inward lunar - Regular throw Inward toss Inward Lunar",
      "Sweets Special Juggle Spike",
      "2 Turn up, 2 Turn throw to airplane",
      "1.5 airplane - 1.5 lighthouse - 1.5 falling in - 1.5 tradespike",
    ],
  },
  {
    name: "NAKO 2020 Open (Level 3)",
    id: "nako-2020-1-open-l3",
    tricks: [
      "Handle Stall - Ring - Spike Fast Hands",
      "Dub kenflip - Juggle - Dub kenflip - Juggle - Dub kenflip - Jug  Spike",
      "Dub Tap - Juggle - Dub Tap Juggle Spike",
      "Triple - Double - Single Lunar Flip",
      "Inward Stilt Tap Full Flip Inward Stilt",
      "Goon Throw Lighty Insta Trade Downspike",
      "1 turn tap jug tap jug tap jug. spike",
      "Stuntplane Tap Fasthands",
      "Candle Dub kenflip Jug Candle dub throw to airplane",
      "Double Lunar Tre",
    ],
  },
  {
    name: "NAKO 2020 Girls Open",
    id: "nako-2020-1-open-girls",
    tricks: [
      "Lightning Drop Tradespike",
      "One Turn Lunar - Lunar Flip - In",
      "Lighthouse- Inward Lighty Flip - Tradespike",
      "Double Whirlwind (Reg or Inward)",
      "Bird Over Valley - Spike - Earth Turn",
      "Airplane - Double Jumping Stick",
      "One Turn Airplane, 1.5 Swap Spike",
      "Around USA",
      "Opposite Hand Bird",
      "Double Gunslinger",
      "Inward Lunar - Inward Lunar Flip - Tradespike",
      "Candle, Kenflip Candle, Downspike",
      "Stunt Plane Flip",
      "Juggle to Spike",
      "Airplane, Double Tap Airplane",
      "Stilt, Trade Downspike",
      "Big cup, Turntable Kenflip Spike",
      "Lunar, 180 Lunar Rover to Inward Lunar - Spike",
      "Cliff Hanger Flip, in",
      "Around Underbird",
    ],
  },
];

export default comps;
